openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Manage My Money API'
  description: 'An API to access my financial information'

servers:
  - description: Dev Server
    url: http://localhost:8080/api

paths:
  /accounts:
    get:
      description: Get all accounts
      tags:
        - accounts
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Accounts'

    post:
      description: Create an account
      tags:
        - accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountInput'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'

  /accounts/{id}:
    get:
      description: Get a specific account
      tags:
        - accounts
      parameters:
        - in: path
          name: id
          required: true
          description: identifier of the account
          schema:
            type: number
            example: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        404:
          $ref: '#/components/responses/NotFound'

    put:
      description: Update an account
      tags:
        - accounts
      parameters:
        - in: path
          name: id
          required: true
          description: identifier of the account
          schema:
            type: number
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        404:
          $ref: '#/components/responses/NotFound'

    delete:
      description: Delete an account
      tags:
        - accounts
      parameters:
        - in: path
          name: id
          required: true
          description: identifier of the account
          schema:
            type: number
            example: 1
      responses:
        204:
          $ref: '#/components/responses/NoContent'
        404:
          $ref: '#/components/responses/NotFound'

  /categories:
    get:
      description: Get all categories
      tags:
        - categories
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categories'

    post:
      description: Create an category
      tags:
        - categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryInput'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'

  /categories/{id}:
    get:
      description: Get a specific category
      tags:
        - categories
      parameters:
        - in: path
          name: id
          required: true
          description: identifier of the category
          schema:
            type: number
            example: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        404:
          $ref: '#/components/responses/NotFound'

    put:
      description: Update an category
      tags:
        - categories
      parameters:
        - in: path
          name: id
          required: true
          description: identifier of the category
          schema:
            type: number
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        404:
          $ref: '#/components/responses/NotFound'

    delete:
      description: Delete an category
      tags:
        - categories
      parameters:
        - in: path
          name: id
          required: true
          description: identifier of the category
          schema:
            type: number
            example: 1
      responses:
        204:
          $ref: '#/components/responses/NoContent'
        404:
          $ref: '#/components/responses/NotFound'

  /transactions:
    get:
      description: Get all transactions
      tags:
        - transactions
      parameters:
        - in: query
          name: account
          required: false
          description: Gets transactions for the specified account
          schema:
            type: number
            example: 1
        - in: query
          name: groupByCategory
          required: false
          description: Gets transaction summaries by category
          schema:
            type: boolean
            example: true
        - in: query
          name: startDate
          required: false
          description: |
                          Gets transaction summaries for txn dates on or after
                          startDate (valid when groupByCategory is specified)
          schema:
            type: string
            example: '2018-01-01'
        - in: query
          name: endDate
          required: false
          description: |
                          Gets transaction summaries for txn dates on or before
                          endDate (valid when groupByCategory is specified)
          schema:
            type: string
            example: '2018-12-31'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Transactions'
                  - $ref: '#/components/schemas/TransactionSummariesByCategory'

    post:
      description: Create a transaction
      tags:
        - transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransactionInput'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'

  /transactions/{id}:
    get:
      description: Get a specific transaction
      tags:
        - transactions
      parameters:
        - in: path
          name: id
          required: true
          description: identifier of the transaction
          schema:
            type: number
            example: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        404:
          $ref: '#/components/responses/NotFound'

    put:
      description: Update a transaction
      tags:
        - transactions
      parameters:
        - in: path
          name: id
          required: true
          description: identifier of the transaction
          schema:
            type: number
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        404:
          $ref: '#/components/responses/NotFound'

    delete:
      description: Delete an transaction
      tags:
        - transactions
      parameters:
        - in: path
          name: id
          required: true
          description: identifier of the transaction
          schema:
            type: number
            example: 1
      responses:
        204:
          $ref: '#/components/responses/NoContent'
        404:
          $ref: '#/components/responses/NotFound'

components:
  responses:
    NoContent:
      description: NoContent
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Account:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: 'BofA Checking'

    Accounts:
      type: array
      items:
        $ref: '#/components/schemas/Account'

    CreateAccountInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: 'BofA Checking'

    Category:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: 'Transport'

    Categories:
      type: array
      items:
        $ref: '#/components/schemas/Category'

    CreateCategoryInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: 'Transport'

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string

    Transaction:
      type: object
      required:
        - id
        - txnDate
        - payee
        - amount
        - accountId
        - categoryId
      properties:
        id:
          type: number
          example: 1
        txnDate:
          type: string
          description: ISO 8601 format
          example: '2019-01-01'
        payee:
          type: string
          example: 'Whole Foods'
        memo:
          type: string
          example: 'Groceries for soup kitchen'
        amount:
          type: number
          description: Positive for income, negative for expense
          example: -55.74
        accountId:
          type: number
          example: 1
        categoryId:
          type: number
          example: 1

    Transactions:
      type: array
      items:
        $ref: '#/components/schemas/Transaction'

    TransactionSummaryByCategory:
      type: object
      required:
        - catId
        - catName
        - amount
      properties:
        catId:
          type: number
          example: 1
        catName:
          type: string
          example: 'Transport'
        amount:
          type: number
          description: Positive for income, negative for expense
          example: -55.74

    TransactionSummariesByCategory:
      type: array
      items:
        $ref: '#/components/schemas/TransactionSummaryByCategory'

    CreateTransactionInput:
      type: object
      required:
        - txnDate
        - payee
        - amount
        - accountId
        - categoryId
      properties:
        txnDate:
          type: string
          description: ISO 8601 format
          example: '2019-01-01'
        payee:
          type: string
          example: 'Whole Foods'
        memo:
          type: string
          example: 'Groceries for soup kitchen'
        amount:
          type: number
          description: Positive for income, negative for expense
          example: -55.74
        accountId:
          type: number
          example: 1
        categoryId:
          type: number
          example: 1
